### ISSUE TITLE
middleware error 

### ISSUE THREAD

**Issue by hadi-mansoori** [hamedov93/passport-grants#2]
I made a client and secret with php artisan passport: client --client 
after generating token when I use auth:api middle  ware I occurred with below error 
{
    "message": "Unauthenticated."
}

**Comment by hamedov93** [comment]
Can you provide more details/code snippets of your implementation.

The command should be: php artisan passport:client --password
Did you send an access token in the request ?
If so, can you post the code used to issue the token ?

**Comment by hadi-mansoori** [comment]
> Can you provide more details/code snippets of your implementation.
> 
> The command should be: php artisan passport:client --password Did you send an access token in the request ? If so, can you post the code used to issue the token ?

It was my mistake, the problem is solved , thanks

**Comment by hamedov93** [comment]
Good to hear, good luck.
