### ISSUE TITLE
Install this package with Laravel passport 11

### ISSUE THREAD

**Issue by hadi-mansoori** [hamedov93/passport-grants#3]
How can I install this package with Laravel passport 11?

**Comment by hamedov93** [comment]
I'll have to update the package to support Passport 11 and handle any breaking changes if any.

I'll try to do that as soon as possible.

But feel free to create a PR with the update if you have the time.

**Comment by hadi-mansoori** [comment]
Thanks Dear [hamedov93] 
I will definitely do this at the right time, time is very limited at the moment.
